name: deployment-api-prod

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deployment-api.yml'
      - '.github/workflows/deployment-api-prod.yml'
      - 'src/Squidlr/**'
      - 'src/Squidlr.Api/**'
  workflow_dispatch:

jobs:
  deployment:
    uses: ./.github/workflows/deployment-api.yml
    with:
      environment: prod
    secrets: inherit    
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write