name: deployment-api-dev

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/deployment-api.yml'
      - '.github/workflows/deployment-api-dev.yml'
      - 'src/Squidlr/**'
      - 'src/Squidlr.Api/**'
  workflow_dispatch:

jobs:
  deployment:
    uses: ./.github/workflows/deployment-api.yml
    with:
      environment: staging
    secrets: inherit
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write